### ISSUE TITLE
Scrape KEDA metric server (port 9022)

### ISSUE THREAD

**Issue by rgordill** [openshift/custom-metrics-autoscaler-operator#28]
Thanks to #9, now it is possible to select monitoring the namespace where the autoscaler is deployed.

Now, we need to expose the metrics-api-server metrics port (9022) so the prometheus from the cluster scrapes it automatically, using ServiceMonitor or PodMonitor (See examples at https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md)

### Use-Case

Get the autoscaler metrics automatically in prometheus and the observability console.

### Specification

- Expose metrics-api-server metrics port.
- Define a ServiceMonitor or PodMonitor to add the target to prometheus using the operator CRs.

**Comment by joelsmith** [comment]
Fixed by #35 and #33 
/close
