### ISSUE TITLE
Namespace should be configured to be monitored by cluster monitoring

### ISSUE THREAD

**Issue by rgordill** [openshift/custom-metrics-autoscaler-operator#9]
When deployed through OLM, the default namespace (openshift-keda) does not contain the label to be included in the cluster monitoring (openshift.io/cluster-monitoring: "true"), so no service monitors can be added.

### Use-Case

Have a concrete monitoring what keda is doing (events, metrics, etc)

### Specification

- This is the first needed feature to include automatically keda in the cluster monitoring space.

**Comment by joelsmith** [comment]
As far as I can tell, there isn't any way for us to fix this. The namespace is created by the OpenShift console as part of the install, and there is no option for us to tell the console how to annotate the newly-created namespace.

**Comment by joelsmith** [comment]
That looks like an enhancement proposal in `implementable` state, not documentation. Are you sure that the proposal was implemented? If so, we can certainly add the annotation, but it still looks as though the user is required to check a box during installation, right?
